apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-replica
  namespace: argocd
spec:
  ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/replicas
  project: default
  source:
    repoURL: 'https://github.com/ivofulco/argocd-app-example.git'
    path: dev 
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true