apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: multiple-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/argoproj/argocd-example-apps.git'
    path: guestbook
    targetRevision: master
    repoURL: 'https://github.com/ivofulco/k8s-app-simple.git'
    path: example/my-cluster 
    targetRevision: HEAD    
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true